# https://taskfile.dev

version: "3"

vars:
  VERSION: "1.14.0"

tasks:
  all:
    cmds:
      - task dart
      - task go
      - task axios
      # - task python
  build:
    desc: "使用 Dart 工具构建所有 SDK"
    cmds:
      - dart pub get
      - dart run bin/puupee_sdk_generator.dart build
  dart:
    cmds:
      - dart pub get
      - dart run bin/puupee_sdk_generator.dart dart --output-dir ../puupee_api_client
  go:
    cmds:
      - rm -rf ../puupee-api-go/*
      - java -jar openapi-generator-cli.jar generate -g go -o ../puupee-api-go -c configs/go.json -i swagger.json --git-user-id puupee --git-repo-id puupee-api-go --release-note update --artifact-version {{.VERSION}}
      - cd ../puupee-api-go/ && go mod tidy && git add . && git commit -a -m "update" && git push origin master --tags
  axios:
    cmds:
      - rm -rf ../puupee-api-axios/*
      - java -jar openapi-generator-cli.jar generate -g typescript-axios -o ../puupee-api-axios -c configs/axios.json -i swagger.json --skip-validate-spec --git-user-id puupee --git-repo-id puupee-api-axios --release-note update --artifact-version {{.VERSION}}
      - cd ../puupee-api-axios/ && yarn install && git add . && git commit -a -m "update" && git push origin main --tags
  python:
    cmds:
      - rm -rf ../puupee-api-python/*
      - java -jar openapi-generator-cli.jar generate -g python-legacy -o ../puupee-api-python -c configs/python.json -i swagger.json --skip-validate-spec --git-user-id puupee --git-repo-id puupee-api-python --release-note update --artifact-version {{.VERSION}}
      # - cd ../puupee-api-python/ && pip3 install -r requirements.txt && git add . && git commit -a -m "update" && git push origin main
      - cd ../puupee-api-python/ && git add . && git commit -a -m "update" && git push origin main --tags
  update-self:
    cmds:
      - git add . && git commit -a -m "update" && git tag v{{.VERSION}} && git push origin main --tags
